#!/usr/bin/env bash
# Transfers a file from client to server

source_file="$1"
host="$2"
user="$3"
identity_file="$4"

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$identity_file" "$source_file" "$user"@"$host":~/
fi
