#!/usr/bin/env bash
# Script to install nginx and configure

# Update package lists
sudo apt update
sudo apt ugrade

# Install Nginx
sudo apt-get -y install nginx

# Stop Nginx (in case it's already running)
sudo service nginx stop

# edit config file to listen on port 80
sudo sed -i "s/listen [^;]*;/listen 80;/" /etc/nginx/sites-available/default

# Create a simple index.html file
sudo echo "Hello World!" > /var/www/html/index.html

# Change ownership of the HTML file (optional, but good practice)
sudo chown -R www-data:www-data /var/www/html

# Restart Nginx (using service instead of systemctl)
sudo service nginx restart
