#!/usr/bin/env bash
# Configure server to redirect

sudo service nginx stop

new_site="https:\/\/charis.vzy.io\/"
string1="server_name _;"
string2="$string1\n\n\tlocation \/redirect_me {\n\t\trewrite ^ $new_site permanent;\n\t}"

sudo sed -i s/"$string1"/"$string2"/ /etc/nginx/sites-available/default

sudo service nginx restart
