#!/usr/bin/env bash
# Configure an Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page.

# Update package lists
sudo apt update
sudo apt ugrade

# Install Nginx
sudo apt-get -y install nginx

sudo service nginx stop