#!/usr/bin/env bash
# Create custom http response header

# Updating Packages before performing installations
sudo apt-get update
sudo apt -y upgrade
sudo apt-get install -y nginx

# Creating an index.html page
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_site="https:\/\/charis.vzy.io\/"
string1="server_name _;"
string2="$string1\n\n\tlocation \/redirect_me {\n\t\trewrite ^ $new_site permanent;\n\t}"
sudo sed -i s/"$string1"/"$string2"/ /etc/nginx/sites-available/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
old_string="server_name _;"
new_string="$old_string\n\n\terror_page 404 \/custom_404.html;"
sudo sed -i s/"$old_string"/"$new_string"/ /etc/nginx/sites-available/default

# Creating an HTTP response header
sudo sed -i 's/http {/http {\n\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf

# Restart nginx after implementing changes
sudo service nginx restart
