#!/usr/bin/env bash
# A script that installs and configures HAproxy on server

#WEB01_IP="54.144.157.5"
#WEB02_IP="54.210.3.114"
conf_file="/etc/haproxy/haproxy.cfg"

sudo apt-get update
sudo apt upgrade -y
sudo apt-get install -y haproxy

# backup config file before making changes
#cp $HAPROXY_CFG ${HAPROXY_CFG}.bak

conf="
frontend charis_http
        bind *:80
        mode http
        default_backend charis_servers

backend charis_servers
        balance roundrobin
        mode http
        server 436725-web-01 54.236.49.42:80 check
        server 436725-web-02 100.25.204.17:80 check
"
echo "$conf" | sudo tee -a "$conf_file"

# load config file
sudo haproxy -f "$conf_file"

# enable haproxy to be started by init script
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
