#!/usr/bin/env bash
# create a mysql backup and compress

if [ $# -ne 1 ]; then
  echo "Usage: $0 <mysql_root_password>"
  exit 1
fi

PASSWORD=$1

# Generate the MySQL dump
sudo mysqldump -u root -p"$PASSWORD" --all-databases > backup.sql

# Get the current date
CURRENT_DATE=$(date +'%d-%m-%Y')

# Compress the MySQL dump into a tar.gz archive
sudo tar -czvf "$CURRENT_DATE".tar.gz backup.sql
