#!/usr/bin/env bash
# This script prints Best school 10 times, displays bad luck
#+ on the 4th iteration and good luck on the 8th

counter=0
while [ $counter -lt 10 ]; do
        if [ $counter = 3 ]; then
                echo "bad luck"
	elif [ $counter = 7 ]; then
                echo "good luck"
	else
		echo "Best School"
        fi
        ((counter++))
done
