#!/usr/bin/env bash
# Script that reads the content of etc/passwd

IFS=':'

# Open /etc/passwd file for reading
while IFS=: read -r username _ userid _ _ homedir _; do
	# Print username, userid, and homedir
	echo "$username:$userid:$homedir"
done < /etc/passwd
