#!/usr/bin/env bash
# Script that reads the content of etc/passwd as a story

IFS=':'

# Open /etc/passwd file for reading
while IFS=: read -r username password userid groupid uidinfo homedir cmdshell; do
	# Print username, userid, and homedir
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $uidinfo"
done < /etc/passwd
