#!/usr/bin/env bash
# This script prints Best school 10 times and hi on the 9th time

counter=0
while [ $counter -lt 10 ]; do
	if [ $counter = 8 ]; then
		echo "Best shool"
	else
		echo "Hi"
	fi
	((counter++))
done
