#!/usr/bin/env bash
# This script prints Best school 10 times, displays bad luck
#+ on the 4th iteration and good luck on the 8th

counter=1
while [ $counter -le 20 ]; do
        case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac
        ((counter++))
done
