#!/usr/bin/env bash
#This script prints 12 hours
hours=0
while [ $hours -le 12 ]; do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -lt 60 ]; do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
